.\" Copyright (c) 2016 Lapis Lazuli Texts
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.\"
.TH CJK\-DEFN 1 2016 cjk\-defn cjk\-defn
.SH NAME
cjk\-defn \- console CJK dictionary program
.SH SYNOPSIS
.B cjk\-defn
[options]
[dictionaries]
.SH DESCRIPTION
cjk\-defn is a command-line dictionary program for looking up definitions of
terms and phrases from the CJK languages: Chinese, Japanese, and Korean. Unlike
most other dictionaries, cjk-defn allows you to input entire lines of text, and
shows relevant definitions for all terms and phrases found.
.PP
When invoking this program, the dictionaries to be used should be specified as
arguments to cjk\-defn. By default, definitions are given by longest matching
term. To get definitions for each character, add the suffix \fB/c\fR to the
name of the dictionary.
.PP
.B
$ cjk\-defn cedict cedict/c
.PP
A list of all installed dictionaries can be obtained by invoking cjk\-defn with
the \*(lqhelp\*(rq option.
.PP
.B
$ cjk-defn \-h
.PP
By default, cjk\-defn includes no dictionaries or definitions. These are added
by creating the SQLite database and inserting data into it. You can read more
about creating the database and loading definitions in the README file.
.PP
Any number of dictionaries can be used simultaneously with cjk\-defn, and all
normal output is read from standard input and written to standard output.
.TP
\fB\-h\fR, \fB\-\-help\fR
print usage information and then exit
.TP
\fB\-i\fR, \fB\-\-info=DICT\fR
show more information about a dictionary
.TP
\fB\-v\fR, \fB\-\-verbose\fR
include information useful for debugging
.SH ENVIRONMENT
.TP
\fBCJK_DEFN_DICTS\fR
Default dictionaries to use, separated by spaces.
.SH FILES
.TP
\fB$(PREFIX)/var/lib/cjk-defn/main.sqlite
The SQLite dictionary database.
.TP
\fB$(PREFIX)/var/lib/cjk-defn/dump-database
Dump SQLite database to stdout.
.TP
\fB$(PREFIX)/var/lib/cjk-defn/make-database
Create the SQLite dictionary database.
.TP
\fB$(PREFIX)/var/lib/cjk-defn/vacuum-database
Clean out the SQLite database.
.SH EXIT STATUS
The exit status is 0 on normal termination, and 1 on error.
.SH DIAGNOSTICS
Errors will print a message to the standard error stream. To enable stack
traces for debugging, enable the \*(lqverbose\*(rq option.
.SH BUGS
Please contact the author if any bugs are found, or file a bug report with the
project. Incomplete or inaccurate documentation should be treated as a bug.
.SH AUTHOR
yaoguai <https://github.com/yaoguai/cjk-defn>
