#!/usr/bin/env python3

""" Script for dumping the database. """

import os
import sqlite3
import sys

USAGE = """Usage: dump-database

Dump database to standard output.

"""


def main():
    """Dump database to stdout."""
    if len(sys.argv) > 1 and sys.argv[1] in ('-h', '--help'):
        print(USAGE, end='')
        return 0
    elif len(sys.argv) != 1:
        sys.stderr.write(USAGE)
        return 1
    db_path = os.path.join(os.path.dirname(__file__), 'main.sqlite')
    db_conn = sqlite3.connect(db_path)
    try:
        for line in db_conn.iterdump():
            print(line)
    finally:
        db_conn.close()


if __name__ == '__main__':
    sys.exit(main())
