#!/usr/bin/env python3

""" Script for vacuuming the database. """

import os
import sqlite3
import sys

USAGE = """Usage: vacuum-database

Vacuum the database to recover unused space.

"""


def main():
    """Vacuum the database."""
    if len(sys.argv) > 1 and sys.argv[1] in ('-h', '--help'):
        print(USAGE, end='')
        return 0
    elif len(sys.argv) != 1:
        sys.stderr.write(USAGE)
        return 1
    db_path = os.path.join(os.path.dirname(__file__), 'main.sqlite')
    db_conn = sqlite3.connect(db_path)
    try:
        db_conn.execute('VACUUM')
    finally:
        db_conn.close()
    return 0


if __name__ == '__main__':
    sys.exit(main())
